ci: check longer timeout for autopkgtest
The default value of CI_JOB_TIMEOUT is 1h (3600), but autopkgtest will
not finish in 1 hour generally.

lintian/lintian CI/CD setting of timeout is extended to 3h, but
not true for forked/contributors lintian CI/CD settings - so it always
fail.

This MR aimed to fix warn such a situation in advance.

Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>

diff --git a/debian/salsa-ci.yml b/debian/salsa-ci.yml
--- a/debian/salsa-ci.yml
+++ b/debian/salsa-ci.yml
@@ -28,3 +28,13 @@ variables:
   before_script:
   - apt-get update
   - apt-get install -y ${WORKING_DIR}/lintian_*.deb
+
+# Try to check whether the maximum job timeout is extended to longer one.
+.test-autopkgtest: &test-autopkgtest
+  before_script:
+    - 'echo "CI/CD Settings / General pipelines / Timeout: $CI_JOB_TIMEOUT seconds"'
+    - |
+      if [[ $CI_JOB_TIMEOUT -le 3600 ]]; then
+        echo -e "\e[31;1mERROR: CI/CD Settings / General pipelines / Timeout is too short ($CI_JOB_TIMEOUT). Use longer timeout - e.g. 7200 (2h) is enough.\e[0m"
+        exit 1
+      fi
