* checks/binaries{.desc,}:   + [RA] Add a check for the new "Invalid operation" error from     objdump -T.  Skip shared-lib-without-dependency-information for     files in /usr/lib/debug. * collection/objdump-info:   + [RA] Pass "Invalid operation" errors from objdump -T on to the check     scripts instead of failing.  (Closes: #249435)

diff --git a/collection/objdump-info b/collection/objdump-info
--- a/collection/objdump-info
+++ b/collection/objdump-info
@@ -46,7 +46,19 @@ for bin in `grep ' ELF' <../file-info | cut -d\: -f1`; do
     if head $bin | grep -q 'packed.*with.*UPX'; then
 	echo "objdump: $bin: Packed with UPX" >> ../objdump-info
     else
-	objdump --headers --private-headers -T $bin >> ../objdump-info 2>&1
+	if objdump --headers --private-headers -T $bin >> ../objdump-info 2>&1 ; then
+	    # everything is ok
+	    :
+	else
+	    # If the objdump error is "Invalid operation", we handle it later
+	    # in the check script, since this is the expected output (for now)
+	    # on detached debugging information in /usr/lib/debug.
+	    if objdump -T $bin 2>&1 | grep -q 'Invalid operation$' ; then
+		:
+	    else
+		exit 1
+	    fi
+	fi
     fi
 done
 
